name: Merge Files from Output to Main

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: main
        path: main

    - name: Checkout Output Branch
      uses: actions/checkout@v2
      with:
        ref: output
        path: output

    - name: Copy Files to Main Branch
      run: |
        mkdir -p main/assets/svg
        cp -r output/* main/assets/svg/

    - name: Commit and Push Changes to Main Branch
      run: |
        cd main
        git config --global user.email "2450854008@qq.com"
        git config --global user.name "Country-If"
        git add assets/svg/
        git commit -m "Automated copy of files from output to main" || true
        git push origin HEAD:main || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token进行身份验证